steps:
- name: 'gcr.io/cloud-builders/python'
  args: ['python3', '-m', 'venv', 'local']

- name: 'gcr.io/cloud-builders/python'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    source ./local/bin/activate
    pip install awscli
    /usr/bin/make requirements

- name: 'gcr.io/cloud-builders/python'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    source ./local/bin/activate
    /usr/bin/make check lint

- name: 'gcr.io/cloud-builders/python'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    source ./local/bin/activate
    /usr/bin/make test

- name: 'gcr.io/cloud-builders/python'
  entrypoint: 'bash'
  args: ['/usr/bin/make', 'build']
