steps:
- name: 'ubuntu'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    python3 -m venv local
    source ./local/bin/activate
    make requirements

- name: 'ubuntu'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    source ./local/bin/activate
    pip install awscli
    make check lint

- name: 'ubuntu'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    source ./local/bin/activate
    make test

- name: 'ubuntu'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    apt-get install -y zip
    make build

- name: 'ubuntu'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    export AWS_ACCESS_KEY_ID=$(cat /workspace/aws_access_key_id.txt)
    export AWS_SECRET_ACCESS_KEY=$(cat /workspace/aws_secret_access_key.txt)
    pip install awscli
    make deploy PLATFORM="Google Cloud Build" FUNCTION=$_STAGING_FUNCTION_NAME VERSION=$COMMIT_SHA BUILD_NUMBER=$BUILD_ID

- name: 'ubuntu'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    make testdeployment URL=$_STAGING_URL VERSION=$COMMIT_SHA

- name: 'ubuntu'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    export AWS_ACCESS_KEY_ID=$(cat /workspace/aws_access_key_id.txt)
    export AWS_SECRET_ACCESS_KEY=$(cat /workspace/aws_secret_access_key.txt)  
    pip install awscli
    make deploy PLATFORM="Google Cloud Build" FUNCTION=$_PRODUCTION_FUNCTION_NAME VERSION=$COMMIT_SHA BUILD_NUMBER=$BUILD_ID

- name: 'ubuntu'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    make testdeployment URL=$_PRODUCTION_URL VERSION=$COMMIT_SHA

substitutions:
    _PRODUCTION_URL: https://kca62rvlvf6erpzn4pcfdppbae0qgpqn.lambda-url.us-east-2.on.aws/
    _PRODUCTION_FUNCTION_NAME: ventura-4-production
    _STAGING_FUNCTION_NAME: ventura-4-staging
    _STAGING_URL: https://jv7qmmnbs3ogwhisxftrvrbxte0axvwu.lambda-url.us-east-2.on.aws/
